### ISSUE TITLE
Rails and Ruby upgrades

### ISSUE THREAD

**Issue by moveson** [billwright/rattlesnake_ramble#134]
We're a couple of Rails versions behind at the moment. It would be good to get up to Rails 7. We are also a version behind on the Heroku stack. We are using Heroku-20, but [Heroku-22](https://devcenter.heroku.com/articles/heroku-22-stack) is now available. Heroku-22 requires Ruby 3.1, so the upgrade path needs to reflect that ordering. The Heroku article does not indicate that Ruby 3.1 is required, but I was not able to get OST up to Heroku-22 without first upgrading to Ruby 3.1.

Path to completion:
- [x] Bump Rails to the latest security patch (#138)
- [x] Upgrade Rails to 6.1 (#139)
- [x] Use Rails 6.1 configs (#140)
- [x] Upgrade to Ruby 3.0 (#146)
- [x] Upgrade to Ruby 3.1 (#151)
- [x] Convert to Heroku-22 stack
- [x] Upgrade to Rails 7 (https://github.com/billwright/rattlesnake_ramble/pull/161)
- [x] Use Rails 7 configs
